source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'cortex-ios-sdk_Example', :exclusive => true do
  pod "DataCortex", :path => "../"
end

target 'cortex-ios-sdk_Tests', :exclusive => true do
  pod "DataCortex", :path => "../"


end
